### ISSUE TITLE
Server doesn't respond to multiple clients

### ISSUE THREAD

**Issue by ErikPitko** [kashimAstro/SimpleNetwork#4]
Even though server seems to be made with multiple connections in mind it wont respond to multiple clients as it will overwrite newsockfd on every new connection, I'm sorry if that's how it was meant to be.

**Comment by kashimAstro** [comment]
hi @ErikPitko , thanks, now i'm traveling, as soon possible i take a look!

**Comment by mendes-jose** [comment]
I modified the code by making a non blocking receive() (put it on a thread) and create a message queue where messages are stored with their sockfd (in order to distinguish between clients). Also I put the queue (replancing Message) as non-static member variable so several instances of the server do not write on the same queue. I'll make a pull request soon I guess.

**Comment by kashimAstro** [comment]
thanks for this @mendes-jose , they are overflowing with work during this period
and i have not had a chance to take a look at this problem.

**Comment by kashimAstro** [comment]
I made some changes, this should be solved!
